### ISSUE TITLE
About - Icons are broken when reloading page

### ISSUE THREAD

**Issue by Voyz** [samchillcott/gatsby-starter-dev-portfolio#1]
When visiting /about page and reloading it, the icons break. They only work once navigating away and back to the /about page using the navigation buttons.

### Expected behaviour:

For the icons to correctly display on reload

### Current behaviour: 

Icons don't get displayed after a reload

https://www.loom.com/share/17c2f03e92d54889a63d18deb7258563

**Comment by samchillcott** [comment]
Altered the path for the icons from relative to absolute.
Thanks for logging the issue.
=)
